---
mq_objects:
  - { flag: t, value: channel }
  - { flag: t, value: queue }
  - { flag: t, value: topic }
  - { flag: x, value: sub }
  - { flag: t, value: listener }
  - { flag: t, value: authinfo }

dump_local_dir: /tmp/mq_dumps
target_dump_dir: /tmp/mq_incoming

# Neste lab, cada QM está em UM container só (não multi-instance),
# então cada lista tem 1 item - já corresponde ao nome do container.
qm_definitions:
  QM_PROD1:
    source_hosts: [OLD_SERVER1]
    target_hosts: [NEW_SERVER1]
  QM_PROD2:
    source_hosts: [OLD_SERVER2]
    target_hosts: [NEW_SERVER2]
  QM_PROD3:
    source_hosts: [OLD_SERVER3]
    target_hosts: [NEW_SERVER3]
